name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js v20.x
        uses: actions/setup-node@v3

        with:
          node-version: $(cat .nvmrc)

      - name: Install dependencies
        run: npm install

      - name: Build Next.js site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
